 CREATE TABLE "PTO"."AUDIT_ERRORS_AK" 
   (	"BATCH_NO" VARCHAR2(10 BYTE), 
	"POSTING_DT" DATE, 
	"DRN" VARCHAR2(12 BYTE), 
	"OP_NUM" VARCHAR2(7 BYTE), 
	"QUEUE" VARCHAR2(30 BYTE), 
	"CHG_CODE" VARCHAR2(5 BYTE), 
	"BEFORE" VARCHAR2(200 BYTE), 
	"AFTER" VARCHAR2(200 BYTE), 
	"SEQ" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  
  CREATE TABLE "PTO"."AUDIT_ERRORS_CLC" 
   (	"BATCH_NO" VARCHAR2(10 BYTE), 
	"POSTING_DT" DATE, 
	"DRN" VARCHAR2(12 BYTE), 
	"OP_NUM" VARCHAR2(7 BYTE), 
	"QUEUE" VARCHAR2(30 BYTE), 
	"CHG_CODE" VARCHAR2(5 BYTE), 
	"BEFORE" VARCHAR2(200 BYTE), 
	"AFTER" VARCHAR2(200 BYTE), 
	"SEQ" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
    CREATE TABLE "PTO"."AUDIT_ERRORS_OFC" 
   (	"BATCH_NO" VARCHAR2(10 BYTE), 
	"POSTING_DT" DATE, 
	"DRN" VARCHAR2(12 BYTE), 
	"OP_NUM" VARCHAR2(7 BYTE), 
	"QUEUE" VARCHAR2(30 BYTE), 
	"CHG_CODE" VARCHAR2(5 BYTE), 
	"BEFORE" VARCHAR2(200 BYTE), 
	"AFTER" VARCHAR2(200 BYTE), 
	"SEQ" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
    CREATE TABLE "PTO"."AUDIT_TRAIL" 
   (	"BATCH_NO" VARCHAR2(12 BYTE), 
	"POSTING_DT" DATE, 
	"DRN" VARCHAR2(14 BYTE), 
	"OP_NUM" VARCHAR2(9 BYTE), 
	"QUEUE" VARCHAR2(32 BYTE), 
	"CHG_CODE" VARCHAR2(7 BYTE), 
	"BEFORE" VARCHAR2(200 BYTE), 
	"AFTER" VARCHAR2(200 BYTE), 
	"SEQ" VARCHAR2(22 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE INDEX "PTO"."IX_AUDIT_DRN" ON "PTO"."AUDIT_TRAIL" ("DRN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  
  CREATE TABLE "PTO"."AUDIT_ERRORS" 
   (	"BATCH_NO" VARCHAR2(10 BYTE), 
	"POSTING_DT" DATE, 
	"DRN" VARCHAR2(12 BYTE), 
	"OP_NUM" VARCHAR2(7 BYTE), 
	"QUEUE" VARCHAR2(30 BYTE), 
	"CHG_CODE" VARCHAR2(5 BYTE), 
	"BEFORE" VARCHAR2(200 BYTE), 
	"AFTER" VARCHAR2(200 BYTE), 
	"SEQ" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

    CREATE TABLE "PTO"."USER_MASTER" 
   (	"OP_ID" VARCHAR2(5 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"TITLE" VARCHAR2(15 BYTE), 
	"TEAM" VARCHAR2(25 BYTE), 
	"SHIFT" VARCHAR2(20 BYTE), 
	"OPR_ID" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
 
  
  
  create or replace 
FUNCTION get_user(
      p_op_no IN VARCHAR2)
    RETURN VARCHAR2
  IS
    v_name user_master.name%type;
  BEGIN
    SELECT name INTO v_name FROM user_master WHERE op_id = p_op_no;
    RETURN v_name;
  END get_user;
  
  /
  
  
  CREATE OR REPLACE
  FUNCTION get_drn(
      p_usr_num    IN VARCHAR2,
      p_posting_dt IN DATE,
      p_module     IN VARCHAR2)
    RETURN VARCHAR2
  IS
    drn_output VARCHAR2(32767);
  BEGIN
    SELECT LISTAGG(drn, ', ') WITHIN GROUP (
    ORDER BY op_num)
    INTO drn_output
    FROM audit_errors_all
    WHERE op_num   =p_usr_num
    AND posting_dt = p_posting_dt
    AND rep_module = p_module ;
    RETURN drn_output;
  END;
  /
  
  
