--------------------------------------------------------
--  File created - Monday-November-05-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USER_MASTER
--------------------------------------------------------

  CREATE TABLE "PTO"."USER_MASTER" 
   (	"OP_ID" VARCHAR2(5), 
	"NAME" VARCHAR2(100), 
	"TITLE" VARCHAR2(15), 
	"TEAM" VARCHAR2(25), 
	"SHIFT" VARCHAR2(20), 
	"OPR_ID" VARCHAR2(5)
   ) ;
REM INSERTING into PTO.USER_MASTER
SET DEFINE OFF;
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('18','Stephen Matta, Harvitha','BA','BA','10am-6pm','18');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('43','Terrio, Lindsay','BA','BA','9am-5pm','43');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('223','CSC Operator','CSC','CSC','CSC','223');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('37','Tugade, August','CSC','CSC','NA','37');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('167','Aljbour, Moh d','DMO','Bartram, Kim','12pm - 8pm','167');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('465','Anderson, Tracey','DMO','Regan, Matthew','8pm - 4am','465');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('164','Aniekwena, Christopher',null,null,null,'164');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('375','Aroyan, Jack','DMO','Regan, Matthew','PT','375');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('474','Athukorala, Premila','DMO','Potter, Chris','PT','474');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('457','Balasubramanian, Kathirvel','DMO','Bartram, Kim','2pm - 10pm','457');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('293','Banoth, Bindu','DMO','Veinot, Jiah','PT','293');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('168','Bauld, Brett','DMO','Veinot, Jiah','8am - 4pm','168');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('103','Baur, Jacob','DMO','Veinot, Jiah','PT','103');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('496','Botas, Andrew',null,null,null,'496');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('442','Chambers, Jacob',null,null,null,'442');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('136','Chang Keddy, Hsiao Mei','DMO','Bartram, Kim','PT','136');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('416','Charles, Andrew','SDMO','MacDonald, Holly','4pm - 12am','416');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('NA','Chase, Garrett',null,null,null,'NA');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('202','Chen, Rui','DMO','Potter, Chris','Tue - Sat','202');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('371','Cluett-Pepper, Myrtle','DMO','Bartram, Kim','PT','371');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('374','Collins, Heather','DMO','MacDonald, Holly','PT','374');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('401','Collins, Heather','DMO','MacDonald, Holly','PT','401');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('165','Corey, Laurie','DMO','Bartram, Kim','12pm - 8pm','165');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('163','Corkum, David','DMO','Potter, Chris','Tue - Sat','163');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('415','Dal Pont, Marcio','DMO','Regan, Matthew','10pm - 6am','415');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('273','Dawe, Sherry','DMO','Potter, Chris','Tue - Sat','273');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('461','Dayrit, Janine','DMO','Veinot, Jiah','PT','461');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('476','d Entremont, Jenna','DMO','Bartram, Kim','2pm - 10pm','476');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('209','Dimmell, Mackenzie','IO','Ash, Margaret','PT','209');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('204','Dong, Darinan','DMO','MacDonald, Holly','4pm - 12am','204');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('229','Faraz, Fatemeh','DMO','Veinot, Jiah','PT','229');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('172','Fennell, Colleen','DMO','Veinot, Jiah','PT','172');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('74','Fitzharris, Sarah',null,null,null,'74');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('92','Gaudet, Andre','IO','McCabe, Wendy-Lee','PT','92');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('459','Golla, Prathima','DMO','Chandler, Will','PT','459');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('460','Hill, Kayleigh','DMO','Potter, Chris','PT','460');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('376','Holley, Megan','DMO','Chandler, Will','PT','376');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('473','Ines Pintilii, Maria','DMO','Potter, Chris','PT','473');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('400','Jacob, Monsi','DMO','MacDonald, Holly','5pm - 1am','400');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('479','Jarrar, Bader','DMO','Potter, Chris','PT','479');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('115','Jiang, Xiaoyang',null,null,null,'115');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('271','Kakreli, Abhay','SDMO','Bartram, Kim','2pm - 10pm','271');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('213','Kaulback, Lori','IO','Ash, Margaret','4pm - 12am','213');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('458','Kelly, Megan','DMO','Potter, Chris','PT','458');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('171','Kenny, Lee','DMO','MacDonald, Holly','4pm - 12am','171');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('212','Keyghobadi, Arshan','DMO','MacDonald, Holly','4pm - 12am','212');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('81','Kidwai, Hena','DMO','Veinot, Jiah','10am - 6pm','81');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('462','Kumar, Amit','DMO','Regan, Matthew','10pm - 6am','462');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('294','Lake, Jennifer','DMO','LOA','PT','294');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x484','Lake, Michael',null,null,null,'x484');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('127','Lattar, Prabjot','DMO','MacDonald, Holly','PT','127');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('225','MacDonald, Mitchell',null,null,null,'225');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('227','Mackintosh, Jeff','DMO','Veinot, Jiah','10am - 6pm','227');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('272','MacPhee, Annette','DMO','LOA','PT','272');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('217','Maher, Niloo','DMO','Chandler, Will','PT','217');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('481','Marasinghe, Manjula','DMO','Bartram, Kim','PT','481');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('370','Martin, Duncan','DMO','MacDonald, Holly','PT','370');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('495','McCabe, Maeve','DMO','Veinot, Jiah','PT','495');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('99','Meleby, Rina','DMO','Chandler, Will','5pm - 1am','99');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('407','Meredith, Christine','DMO','Regan, Matthew','8pm - 4am','407');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('131','Miller, Jasmine',null,null,null,'131');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('226','O Handley, Liam','DMO','Veinot, Jiah','8am - 4pm','226');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('494','Panagopoulos, Ntina','DMO','Veinot, Jiah','PT','494');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('480','Pinder, Da Nae','DMO','Chandler, Will','PT','480');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('169','Quigley, Hunter','IO','McCabe, Wendy-Lee','PT','169');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('475','Rathnayaka, Samith','DMO','Chandler, Will','PT','475');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('214','Ross, Jarrett','SDMO','MacDonald, Holly','Tue - Sat','214');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('228','Shen, Jiaqi','DMO','MacDonald, Holly','5pm - 1am','228');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('443','Shi, Robert','DMO','Potter, Chris','Tue - Sat','443');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('471','Sweete, Christopher','DMO','Potter, Chris','PT','471');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('404','Swetnam, William','DMO','Regan, Matthew','8pm - 4am','404');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('403','Trivedi, Vatsal','DMO','Regan, Matthew','8pm - 4am','403');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('372','VanNorden, Diane','DMO','MacDonald, Holly','PT','372');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('413','Wang, Nan','DMO','Regan, Matthew','PT','413');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('274','Wangari, Yvonne','DMO','Bartram, Kim','PT','274');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('412','White, Shamika','DMO','Regan, Matthew','PT','412');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('68','Whitman, Helen','DMO','Veinot, Jiah','10am - 6pm','68');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('210','Wolthausen, Francine','DMO','MacDonald, Holly','4pm - 12am','210');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('411','Xia, Tian','DMO','Regan, Matthew','10pm - 6am','411');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('108','Yambayamba, Taza',null,null,null,'108');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('493','Yee, Laura','DMO','Chandler, Will','PT','493');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('113','Young, Margaret A','DMO','Chandler, Will','5pm - 1am','113');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('215','Yu, Fan',null,null,null,'215');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('492','Yuan, Ping','DMO','Chandler, Will','PT','492');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('485','Zhang, Yaning','DMO','Potter, Chris','PT','485');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('180','Zimmel, Shelley',null,null,null,'180');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('500','Jubair, MD Abdullah-Al','DMO','Bartram, Kim','PT','500');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('501','Gallant, Kate','DMO','Bartram, Kim','PT','501');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('502','Borja, Carmichael','DMO','Chandler, Will','PT','502');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('510','Zhao, Xiangyu','DMO','Potter, Chris','PT','510');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('511','Yang, Hao','DMO','Bartram, Kim','PT','511');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('512','Kalzi, Habib','DMO','MacDonald, Holly','PT','512');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('516','Amararathna, Madumani','DMO','Potter, Chris','PT','516');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('517','Ducey, Matthew','DMO','Bartram, Kim','PT','517');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('518','McMullin, Mitchell','DMO','Potter, Chris','PT','518');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('519','Mingo, Paige','DMO','Potter, Chris','PT','519');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('91','Adams, Seth','IO','Wendy-Lee','10am-6pm','91');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('216','Ayanampudi, Siva','IO','Margaret','4pm-12am','216');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('87','Connolly, Kyle','IO','Wendy-Lee','10am-6pm','87');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('107','Jeldani, Hooman','IO','Wendy-Lee','10am-6pm','107');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('306','LeBlanc, Luc','IO','Margaret','10am-6pm','306');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('489','MacPherson, Kaleigh','IO','Margaret','10am-6pm','489');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('484','McCabe, Luke','IO','NA','LOA','484');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('467','O Brien, Kyle','IO','Margaret','4pm-12am','467');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('308','Osmond, Jennifer','IO','Wendy-Lee','8:30am-4:30pm','308');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('311','Ryter, Dale','IO','Margaret','8:30am-4:30pm','311');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('126','Small, Dhiachelbi','IO','Wendy-Lee','10am-6pm','126');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('303','Staples, Sean','IO','Wendy-Lee','10am-6pm','303');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('304','Sutherland, Janelle','IO','Wendy-Lee','10am-6pm','304');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('301','Warren-Murphy, Alison','IO','Wendy-Lee','10am-6pm','301');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('104','Wilson, Samara','IO','Margaret','4pm-12am','104');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('25','Duguay, Joey','MGR','MGR','10am-6pm','25');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('26','Fraser, Trevor','MGR','MGR','9am-5pm','26');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('41','Kelly, Eileen','MGR','MGR','8:30am-4:30pm','41');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('466','Lapointe, Tracy','MGR','MGR','2pm-10pm','466');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('0','System','MGR','ALL','NA','0');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('79','VanHorne, Kelly','MGR','MGR','2pm-10pm','79');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('10','Wallace, Mike','MGR','MGR','8:30am-4:30pm','10');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('96','White, Thomas','MGR','MGR','10am-6pm','96');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x30','Adekoya, Adeola','NA','NA','NA','30');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x94','Almousa, Mohammed','NA','NA','NA','94');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x123','Butler, Kayleigh','NA','NA','NA','x123');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x29','Cater, Tracy','NA','NA','NA','x29');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x115','Cheleyeva, Maral','NA','NA','NA','x115');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x75','Coughlan, Matthew D','NA','NA','NA','x75');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x28','Devoe, Lori','NA','NA','NA','x28');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x40','Estabrooks, Catherine','NA','NA','NA','x40');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x34','Fox, Shauna','NA','NA','NA','34');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x166','Galway, Sean','NA','NA','NA','166');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x97','Grinberg, Victoria','NA','NA','PT','97');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x67','Guo, Chelsea','NA','NA','NA','67');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x114','Hicks, Logan','NA','NA','NA','114');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x132','Ibeh, Charles','NA','NA','NA','x132');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x46','Jacobi, Laura K','NA','NA','NA','46');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x115','Keen, Danielle','NA','NA','NA','x115');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('211','Kumar, Shiva','NA','NA','NA','211');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x85','Lohnes, Jeremy','NA','NA','NA','85');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x14','MacDougall, Andrew','NA','NA','NA','x14');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x104','Magee, Debbie','NA','NA','NA','x104');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x45','Matheson, Stewart','NA','NA','NA','45');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x93','Matta, Stephen','NA','NA','NA','93');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x90','Maughan, Kevin','NA','NA','NA','x90');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x129','McDowell, Peter','NA','NA','NA','129');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x13','Nasier, Michael','NA','NA','NA','x13');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x17','Nauffts, Zachary','NA','NA','NA','x17');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x130','Nwaigwe, Kennedy','NA','NA','NA','x130');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x23','O Brien, Alison','NA','NA','NA','x23');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x84','Okere, Stanley','NA','NA','NA','x84');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('49','Okihiro, Jonathan','NA','NA','NA','49');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x47','Palem, Neelima','NA','NA','NA','x47');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x37','Palmeter, Melinda','NA','NA','NA','x37');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x133','Park, Sunghyun','NA','NA','NA','x133');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x102','Prisciak, Andrew','NA','NA','NA','x102');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x42','Rahiman, Kamran','NA','NA','NA','x42');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x128','Ru, Dai','NA','NA','NA','x128');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x42','Skerry, Joan','NA','NA','NA','x42');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x36','Stefan, Jonathon','NA','NA','NA','36');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x76','Tompkins, Kevin','NA','NA','NA','76');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x112','Wilson, Jessica','NA','NA','NA','112');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x483','Wu, Han','NA','NA','NA','x483');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x125','Yuan, Matt','NA','NA','NA','125');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('48','Afkari, Kioumars','SDMO','Veinot, Jiah','10am - 6pm','48');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('134','Al misleh, Fida','SDMO','Veinot, Jiah','10am - 6pm','134');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('208','Charles, Marcia','SDMO','Regan, Matthew','10pm - 6am','208');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('73','Ding, Cheng','SIO','Ash, Margaret','PT','73');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('38','Fournier, Luc',null,null,null,'38');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('95','Hanrahan, Ed',null,null,null,'95');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('50','JeBailey, John','SDMO','Chandler, Will','5pm - 1am','50');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('27','Kelly, Ryan','SDMO','Regan, Matthew','10pm - 6am','27');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('187','Mitchell, Maurie','SDMO','Chandler, Will','5pm - 1am','187');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('24','Mowat, Susan',null,null,null,'24');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('78','Oduche, Lilian',null,null,null,'78');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('544','Vemuri, Ravishankar','DMO','Regan, Matthew','10pm - 6am','544');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x98','Potter, Chris','SDMO','Lapointe, Tracy','Tue - Sat','x98');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('203','Potter, Chris','SDMO','Lapointe, Tracy','Tue - Sat','203');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('109','Rivera, Laarni Joy','SDMO','Bartram, Kim','12pm - 8pm','109');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('105','Schaus, Linda','SDMO','Chandler, Will','5pm - 1am','105');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('119','Sears, Heather','SIO','McCabe, Wendy-Lee','12pm - 8pm','119');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('300','Skanes, Shannon','SDMO','MacDonald, Holly','Tue - Sat','300');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('170','Thomas, Tijo','SDMO','Chandler, Will','5pm - 1am','170');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('414','Thompson, Sanjay','SDMO','Regan, Matthew','10pm - 6am','414');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('110','Van den Heuvel, Arlene','SDMO','Chandler, Will','5pm - 1am','110');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('80','Barnes, Andrew','SIO','Wendy-Lee','8:30am-4:30pm','80');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('181','Gamage, Champika','SIO','Margaret','4pm-12am','181');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('101','Hackett, Lindsay','SIO','Wendy-Lee','8:30am-4:30pm','101');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('307','Jones, Justice','SIO','Margaret','4pm-12am','307');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('KM','Mah, Katherine','SIO','Margaret','4pm-12am','KM');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('44','Mohammed, Junaid','SIO','Margaret','10am-6pm','44');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('309','Phillips, Margaret','SIO','Wendy-Lee','8:30am-4:30pm','309');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('142','Stubbs, Javaughn','SIO','Margaret','10am-6pm','142');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('310','Stutt-Mueller, Nathan','SIO','Margaret','8am-4pm','310');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('297','Sullivan, Nicole','SIO','Margaret','8am-4pm','297');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('302','Zimmerman, Genevieve','SIO','Wendy-Lee','8:30am-4:30pm','302');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('77','Alcantara, Marialuz','Tech/ BCP','Toronto','NA','77');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('88','Artates, Elize khristine','Tech/ BCP','Toronto','NA','88');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('120','Augusto, Manny','Tech/ BCP','Toronto','NA','120');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('54','Banjo, Femi','Tech/ BCP','Toronto','NA','54');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('89','Bridgelal, Anson','Tech/ BCP','Toronto','NA','89');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('52','Caparal, Dar','Tech/ BCP','Toronto','NA','52');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('7','Chaves, Ricardo','Tech/ BCP','Toronto','NA','7');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('63','Chen See, Hugo','Tech/ BCP','Toronto','NA','63');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('5','Chui, Nancy','Tech/ BCP','Toronto','NA','5');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('11','Gallant, Laurie (S)','Tech/ BCP','Toronto','NA','11');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('141','Gibson-Penner, Sandra','Tech/ BCP','Toronto','NA','141');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('64','Goll, Jennifer','Tech/ BCP','Toronto','NA','64');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('4','Hill, Glenn','Tech/ BCP','Toronto','NA','4');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('82','Hutchings, Wesley','Tech/ BCP','Toronto','NA','82');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('66','Johnson, Clarita','Tech/ BCP','Toronto','NA','66');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('15','Jones, Kevin','Tech/ BCP','Toronto','NA','15');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('61','Jones, Matthew','Tech/ BCP','Toronto','NA','61');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('53','Ko, Elaine','Tech/ BCP','Toronto','NA','53');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x22','Lam, Jason W','Tech/ BCP','NA','NA','x22');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('60','Lau, Carolyn','Tech/ BCP','Toronto','NA','60');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('70','Les Strange, Becky','Tech/ BCP','Toronto','NA','70');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('62','Leung, Kary','Tech/ BCP','Toronto','NA','62');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('56','Lin, Francis','Tech/ BCP','Toronto','NA','56');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('12','Lorenz, Julie','Tech/ BCP','Toronto','NA','12');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x97','Loyd, hans','Tech/ BCP','Toronto','NA','x97');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('51','MacLeod, Ryan','Tech/ BCP','Toronto','NA','51');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('59','Martinez, Brian','Tech/ BCP','Toronto','NA','59');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('35','Mathews, Bridget','Tech/ BCP','Toronto','NA','35');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('71','Moss, Roland','Tech/ BCP','Toronto','NA','71');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('200','Murfin, Gay','Tech/ BCP','Toronto','NA','200');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('135','Pineo, Susan','Tech/ BCP','NA','NA','135');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('6','Ramai, Trevor','Tech/ BCP','Toronto','NA','6');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('21','Rhaman, Shawn','Tech/ BCP','Toronto','NA','21');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('86','Riberio, Brian','Tech/ BCP','Toronto','NA','86');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('16','Shebunchak, Dan D','Tech/ BCP','Toronto','NA','16');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('x108','Shetty, Anokh Dayananda','Tech/ BCP','Toronto','NA','x108');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('20','Shimla, Aaron','Tech/ BCP','Toronto','NA','20');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('201','Singh, Vaibhav S','Tech/ BCP','Toronto','NA','201');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('56','Siscar, Reichel','Tech/ BCP','Toronto','NA','56');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('65','Tan, Nelia','Tech/ BCP','Toronto','NA','65');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('58','Uy, Jordan','Tech/ BCP','Toronto','NA','58');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('19','Verhoeven, Hank','Tech/ BCP','Toronto','NA','19');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('72','Wang, Rick','Tech/ BCP','Toronto','NA','72');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('55','Wei, Xin','Tech/ BCP','Toronto','NA','55');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('3','Wetherald, Albert','Tech/ BCP','Toronto','NA','3');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('83','Za, Mary','Tech/ BCP','Toronto','NA','83');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('490','Ash, Margaret','TL','Eileen','1pm-9pm','490');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('32','Bartram, Kimberley','TL','Trevor','4pm-12am','32');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('33','Chandler, William','TL','Trevor','5pm-1am','33');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('425','MacDonald, Holly','TL','Kelly','5pm-1am','425');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('39','Mccabe, Wendy-Lee','TL','Eileen','10am-6pm','39');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('100','Regan, Matthew','TL','Kelly','11pm-7am','100');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('69','Veinot, Jiah','TL','Trevor','12pm-8pm','69');
Insert into PTO.USER_MASTER (OP_ID,NAME,TITLE,TEAM,SHIFT,OPR_ID) values ('206','Amul, Ana','Toronto','NA','NA','206');
